export const FeatureData = [
    {
      brand: "Velarro",
      name: "Year of the Horse Limited Edition 2026",
      isNew: true,
      ringGauge: 55,
      diameter: "2.2 cm",
      lengthInch: '6 1/2"',
      lengthMm: "16.5 cm",
      smokingTime: "70-90min",
      intensity: 3,
      format: "Special Toro",
    },
    {
      brand: "Velarro",
      name: "Year of the Snake Limited Edition 2025",
      isNew: true,
      ringGauge: 52,
      diameter: "2.06 cm",
      lengthInch: '6"',
      lengthMm: "15.2 cm",
      smokingTime: "60-80min",
      intensity: 4,
      format: "Grand Toro",
    },
    {
      brand: "Velarro",
      name: "Year of the Dragon Limited Edition 2024",
      isNew: false,
      ringGauge: 58,
      diameter: "2.3 cm",
      lengthInch: '5 1/2"',
      lengthMm: "14 cm",
      smokingTime: "65-85min",
      intensity: 4,
      format: "Perfecto",
    },
    {
      brand: "Velarro",
      name: "Year of the Rabbit Limited Edition 2023",
      isNew: false,
      ringGauge: 50,
      diameter: "2.0 cm",
      lengthInch: '6 1/8"',
      lengthMm: "15.6 cm",
      smokingTime: "70-90min",
      intensity: 2,
      format: "Toro",
    },
    {
      brand: "Velarro",
      name: "Year of the Tiger Limited Edition 2022",
      isNew: false,
      ringGauge: 54,
      diameter: "2.14 cm",
      lengthInch: '6"',
      lengthMm: "15.2 cm",
      smokingTime: "75-95min",
      intensity: 3,
      format: "Robusto Extra",
    },
    {
      brand: "Velarro",
      name: "Year of the Ox Limited Edition 2021",
      isNew: false,
      ringGauge: 56,
      diameter: "2.22 cm",
      lengthInch: '5 3/4"',
      lengthMm: "14.6 cm",
      smokingTime: "60-80min",
      intensity: 4,
      format: "Gordo",
    },
    {
      brand: "Velarro",
      name: "Year of the Rat Limited Edition 2020",
      isNew: false,
      ringGauge: 48,
      diameter: "1.9 cm",
      lengthInch: '6 1/4"',
      lengthMm: "15.9 cm",
      smokingTime: "65-85min",
      intensity: 3,
      format: "Corona Gorda",
    },
  ];