import { Cigar } from "@/types/cigar";

const cigarData: Cigar[] = [
  {
    id: 1,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Limited Compendium",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 2,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Masterpiece Blend",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 3,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Oro Oscuro",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 4,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Opus Magnifique",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 5,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Platinum Celebration",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 6,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Platinum Celebration",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 7,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Platinum Celebration",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 8,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Platinum Celebration",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },
  {
    id: 9,
    image: "/cigar6.avif",
    badge: "Top Gift",
    title: "Platinum Celebration",
    size: "52 RG",
    length: "7.5 in",
    burnTime: "100–120 min",
    intensity: 4,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    brand: "GRAN CHURCHILL",
  },

];

export default cigarData;