// import { Cigar } from "@/types/cigar";

export type ProductFilterItem = {
  id: number;
  series?: string;
  image: string;
  badge: string;
  title: string;
  format: string;
  hexCode: string;
  ringGauge: number | null;
  length: string;
  lengthCm: string;
  diameterCm: string;
  duration: string;
  burnTime: string;
  enjoymentTime: number;
  intensity: number;
  body: number;
  flavors: string;
  packaging: string[];
  for: string[];
  origin: {
    wrapper: string;
    binder: string;
    filler: string;
  };
  pairings: string[];
  brand: string;
  size: string;
};

const data: ProductFilterItem[] = [
  {
    id: 1,
    series: "Collector",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959156545-category-1-masterpiece-blend.webp",
    badge: "Collector",
    title: "Limited Compendium",
    format: "Salomones",
    hexCode: "#C9A44C",
    ringGauge: 57,
    length: "7.2 in",
    lengthCm: "18.2 cm",
    diameterCm: "2.26 cm",
    duration: "120-130 min",
    burnTime: "120–130 min",
    enjoymentTime: 125,
    intensity: 5,
    body: 5,
    flavors: "Dark chocolate, prune, vintage leather, cedar wood, roasted nuts",
    packaging: ["Box of 10", "Single"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Corojo 99 Maduro",
      binder: "Criollo 98",
      filler: "Criollo + Piloto Cubano",
    },
    pairings: ["Rum", "Bourbon Whiskey", "Espresso"],
    brand: "SALOMONES",
    size: "57 RG",
  },
  {
    id: 2,
    series: "Collector",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959156545-category-1-masterpiece-blend.webp",
    badge: "Collector",
    title: "Masterpiece Blend",
    format: "Diademas",
    hexCode: "#C9A44C",
    ringGauge: 52,
    length: "8.5 in",
    lengthCm: "21.6 cm",
    diameterCm: "2.06 cm",
    duration: "120-140 min",
    burnTime: "120–140 min",
    enjoymentTime: 130,
    intensity: 5,
    body: 5,
    flavors: "Cacao, oak wood, roasted almonds, dark cherries, vintage leather",
    packaging: ["Box of 10", "Single"],
    for: ["Collector"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Criollo + Piloto",
    },
    pairings: ["Rum", "Bourbon Whiskey", "Espresso"],
    brand: "DIADEMAS",
    size: "52 RG",
  },
  {
    id: 3,
    series: "Collector",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959156545-category-1-masterpiece-blend.webp",
    badge: "Collector",
    title: "Oro Oscuro",
    format: "Double Corona",
    hexCode: "#C9A44C",
    ringGauge: 49,
    length: "7.5 in",
    lengthCm: "19 cm",
    diameterCm: "1.94 cm",
    duration: "110-120 min",
    burnTime: "110–120 min",
    enjoymentTime: 115,
    intensity: 5,
    body: 5,
    flavors: "Dark cherries, cacao, roasted coffee, vintage leather, molasses",
    packaging: ["Box of 10", "Single"],
    for: ["Collector"],
    origin: {
      wrapper: "Corojo 99 Maduro",
      binder: "Criollo 98",
      filler: "Criollo + Piloto Cubano",
    },
    pairings: ["Rum", "Whiskey", "Espresso"],
    brand: "DOUBLE CORONA",
    size: "49 RG",
  },
  {
    id: 4,
    series: "Collector",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959156545-category-1-masterpiece-blend.webp",
    badge: "Collector",
    title: "Opus Magnifique",
    format: "Double Corona",
    hexCode: "#C9A44C",
    ringGauge: 49,
    length: "7.6 in",
    lengthCm: "19.3 cm",
    diameterCm: "1.94 cm",
    duration: "110-120 min",
    burnTime: "110–120 min",
    enjoymentTime: 115,
    intensity: 5,
    body: 5,
    flavors: "Dark chocolate, oak wood, leather, roasted coffee, cinnamon",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo + Ometepe",
    },
    pairings: ["Rum", "Bourbon Whiskey", "Espresso"],
    brand: "DOUBLE CORONA",
    size: "49 RG",
  },
  {
    id: 5,
    series: "Heritage",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959204015-category-2-heritage-collection.webp",
    badge: "Collector",
    title: "Heritage Collection",
    format: "Salomones",
    hexCode: "#8C4A3C",
    ringGauge: 57,
    length: "7.2 in",
    lengthCm: "18.2 cm",
    diameterCm: "2.26 cm",
    duration: "110-120 min",
    burnTime: "110–120 min",
    enjoymentTime: 115,
    intensity: 4,
    body: 5,
    flavors: "Dark cherries, roasted coffee, cinnamon, cedar wood, vanilla",
    packaging: ["Box of 10", "Single"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo + Ometepe",
    },
    pairings: ["Rum", "Whiskey Sour", "Espresso"],
    brand: "SALOMONES",
    size: "57 RG",
  },
  {
    id: 6,
    series: "Heritage",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959204015-category-2-heritage-collection.webp",
    badge: "Collector",
    title: "Signature No. 1",
    format: "Perfecto Grande",
    hexCode: "#8C4A3C",
    ringGauge: 54,
    length: "6.5 in",
    lengthCm: "16.5 cm",
    diameterCm: "2.14 cm",
    duration: "85-95 min",
    burnTime: "85–95 min",
    enjoymentTime: 90,
    intensity: 4,
    body: 5,
    flavors: "Cedar, honey, roasted coffee, cashew, brioche",
    packaging: ["Box of 10", "Single"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano + Ometepe",
    },
    pairings: ["Champagne", "Whiskey", "Coffee"],
    brand: "PERFECTO GRANDE",
    size: "54 RG",
  },
  {
    id: 7,
    series: "Heritage",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959204015-category-2-heritage-collection.webp",
    badge: "Aficionado",
    title: "Añejo 10",
    format: "Churchill",
    hexCode: "#8C4A3C",
    ringGauge: 48,
    length: "7.0 in",
    lengthCm: "17.8 cm",
    diameterCm: "1.90 cm",
    duration: "85-95 min",
    burnTime: "85–95 min",
    enjoymentTime: 90,
    intensity: 4,
    body: 5,
    flavors: "Dark chocolate, vintage leather, dried fruit, oak wood, caramel",
    packaging: ["Box of 20", "Box of 10 Tubos"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Piloto Cubano + Ometepe",
    },
    pairings: ["Rum", "Rye Whiskey", "Dark Roast Coffee"],
    brand: "CHURCHILL",
    size: "48 RG",
  },
  {
    id: 8,
    series: "Celebration",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959502876-catagory-3-celebration-series-platinum-celebration.webp",
    badge: "Top Gift",
    title: "Platinum Celebration",
    format: "Gran Churchill",
    hexCode: "#C6CBD3",
    ringGauge: 52,
    length: "7.5 in",
    lengthCm: "19 cm",
    diameterCm: "2.06 cm",
    duration: "100-120 min",
    burnTime: "100–120 min",
    enjoymentTime: 110,
    intensity: 4,
    body: 5,
    flavors: "Vanilla, brioche, roasted coffee, cream, honey",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Gift Giver", "Collector"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Piloto Cubano + Ometepe",
    },
    pairings: ["Champagne", "Whiskey", "Coffee"],
    brand: "GRAN CHURCHILL",
    size: "52 RG",
  },
  {
    id: 9,
    series: "Dark",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1780198884245-black-label-reserve.webp",
    badge: "Aficionado",
    title: "Black Label Reserve",
    format: "Churchill",
    hexCode: "#3A3A3A",
    ringGauge: 50,
    length: "7.0 in",
    lengthCm: "17.8 cm",
    diameterCm: "1.98 cm",
    duration: "90-100 min",
    burnTime: "90–100 min",
    enjoymentTime: 95,
    intensity: 4,
    body: 5,
    flavors: "Roasted nuts, cacao, cedar, pepper, molasses",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Collector", "Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo + Piloto Cubano",
    },
    pairings: ["Bourbon Whiskey", "Rye Whiskey", "Coffee"],
    brand: "CHURCHILL",
    size: "50 RG",
  },
  {
    id: 10,
    series: "Prestige",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959627106-catagory-5-prestige-serires-sovereign-.webp",
    badge: "Aficionado",
    title: "Centennial Reserve",
    format: "Toro Gordo",
    hexCode: "#2F3F63",
    ringGauge: 56,
    length: "6.5 in",
    lengthCm: "16.5 cm",
    diameterCm: "2.22 cm",
    duration: "90-100 min",
    burnTime: "90–100 min",
    enjoymentTime: 95,
    intensity: 5,
    body: 5,
    flavors: "Black pepper, roasted almonds, cacao, oak wood, vintage leather",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo + Piloto",
    },
    pairings: ["Bourbon Whiskey", "Rye Whiskey", "Coffee"],
    brand: "TORO GORDO",
    size: "56 RG",
  },
  {
    id: 11,
    series: "Prestige",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959627106-catagory-5-prestige-serires-sovereign-.webp",
    badge: "Aficionado",
    title: "Sovereign",
    format: "Toro",
    hexCode: "#2F3F63",
    ringGauge: 54,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "2.14 cm",
    duration: "70-80 min",
    burnTime: "70–80 min",
    enjoymentTime: 75,
    intensity: 5,
    body: 5,
    flavors: "Leather, black pepper, cacao, roasted nuts, espresso",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Criollo + Piloto",
    },
    pairings: ["Bourbon Whiskey", "Rum", "Espresso"],
    brand: "TORO",
    size: "54 RG",
  },
  {
    id: 12,
    series: "Prestige",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959627106-catagory-5-prestige-serires-sovereign-.webp",
    badge: "Top Gift",
    title: "Crown Reserve",
    format: "Petit Robusto",
    hexCode: "#2F3F63",
    ringGauge: 50,
    length: "4.0 in",
    lengthCm: "10.1 cm",
    diameterCm: "1.98 cm",
    duration: "35-45 min",
    burnTime: "35–45 min",
    enjoymentTime: 40,
    intensity: 3,
    body: 3,
    flavors: "Hazelnut, cedar, cream, roasted almonds, vanilla",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Gift Giver", "Novice"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Coffee", "Rye Whiskey"],
    brand: "PETIT ROBUSTO",
    size: "50 RG",
  },
  {
    id: 13,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Aficionado",
    title: "Reserve",
    format: "Robusto",
    hexCode: "#E2DBCF",
    ringGauge: 50,
    length: "5.0 in",
    lengthCm: "12.7 cm",
    diameterCm: "1.98 cm",
    duration: "55-65 min",
    burnTime: "55–65 min",
    enjoymentTime: 60,
    intensity: 3,
    body: 4,
    flavors: "Cedar wood, roasted coffee, vanilla, almond, leather",
    packaging: ["Box of 25", "Box of 10", "Single"],
    for: ["Aficionado", "Collector"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano + Ometepe",
    },
    pairings: ["Espresso", "Bourbon Whiskey", "Champagne"],
    brand: "ROBUSTO",
    size: "50 RG",
  },
  {
    id: 14,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Aficionado",
    title: "Grand Cru",
    format: "Toro",
    hexCode: "#E2DBCF",
    ringGauge: 54,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "2.14 cm",
    duration: "70-80 min",
    burnTime: "70–80 min",
    enjoymentTime: 75,
    intensity: 4,
    body: 4,
    flavors: "Hazelnut, dark chocolate, oak wood, brioche, caramel",
    packaging: ["Box of 20", "Pack of 5", "Single"],
    for: ["Aficionado", "Collector"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo 99 + Piloto",
    },
    pairings: ["Rum", "Rye Whiskey", "Cappuccino"],
    brand: "TORO",
    size: "54 RG",
  },
  {
    id: 15,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Top Gift",
    title: "Royal Leaf",
    format: "Churchill",
    hexCode: "#E2DBCF",
    ringGauge: 48,
    length: "7.0 in",
    lengthCm: "17.8 cm",
    diameterCm: "1.90 cm",
    duration: "85-95 min",
    burnTime: "85–95 min",
    enjoymentTime: 90,
    intensity: 3,
    body: 3,
    flavors: "Cream, floral spice, cedar wood, cashew, dried apricots",
    packaging: ["Box of 20", "Box of 10 Tubos"],
    for: ["Collector", "Gift Giver"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Coffee", "Citrus cocktails"],
    brand: "CHURCHILL",
    size: "48 RG",
  },
  {
    id: 16,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Aficionado",
    title: "Imperial",
    format: "Double Corona",
    hexCode: "#E2DBCF",
    ringGauge: 49,
    length: "7.6 in",
    lengthCm: "19.3 cm",
    diameterCm: "1.94 cm",
    duration: "100-120 min",
    burnTime: "100–120 min",
    enjoymentTime: 110,
    intensity: 5,
    body: 5,
    flavors: "Leather, black pepper, cacao, roasted nuts, espresso",
    packaging: ["Box of 25", "Box of 10"],
    for: ["Aficionado"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Criollo + Corojo",
    },
    pairings: ["Bourbon Whiskey", "Espresso", "Dark Rum"],
    brand: "DOUBLE CORONA",
    size: "49 RG",
  },
  {
    id: 17,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Top Gift",
    title: "Estate Series",
    format: "Lonsdale",
    hexCode: "#E2DBCF",
    ringGauge: 42,
    length: "6.5 in",
    lengthCm: "16.5 cm",
    diameterCm: "1.67 cm",
    duration: "65-75 min",
    burnTime: "65–75 min",
    enjoymentTime: 70,
    intensity: 2,
    body: 3,
    flavors: "Cedar, bread, malt, honey, roasted almonds",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Novice", "Gift Giver"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano + Ometepe",
    },
    pairings: ["Cappuccino", "Champagne", "Wheat beer"],
    brand: "LONSDALE",
    size: "42 RG",
  },
  {
    id: 18,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Collector",
    title: "Époque",
    format: "Robusto Extra",
    hexCode: "#E2DBCF",
    ringGauge: null,
    length: "5.5 in",
    lengthCm: "14 cm",
    diameterCm: "2.06 cm",
    duration: "65-75 min",
    burnTime: "65–75 min",
    enjoymentTime: 70,
    intensity: 3,
    body: 4,
    flavors: "Cashew, brioche, vanilla bean, citrus, roasted coffee",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Collector", "Novice"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Coffee", "Cocktails"],
    brand: "ROBUSTO EXTRA",
    size: "52 RG",
  },
  {
    id: 19,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Collector",
    title: "Vintage No. 88",
    format: "Lancero",
    hexCode: "#E2DBCF",
    ringGauge: 38,
    length: "7.5 in",
    lengthCm: "19 cm",
    diameterCm: "1.52 cm",
    duration: "80-90 min",
    burnTime: "80–90 min",
    enjoymentTime: 85,
    intensity: 2,
    body: 3,
    flavors: "Dried flowers, honey, cedar wood, almonds, brioche",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Collector", "Novice"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Cappuccino", "Light Whiskey"],
    brand: "LANCERO",
    size: "38 RG",
  },
  {
    id: 20,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Collector",
    title: "Private Cellar",
    format: "Lancero",
    hexCode: "#E2DBCF",
    ringGauge: 38,
    length: "7.5 in",
    lengthCm: "19 cm",
    diameterCm: "1.52 cm",
    duration: "85-95 min",
    burnTime: "85–95 min",
    enjoymentTime: 90,
    intensity: 3,
    body: 4,
    flavors: "Floral spice, vanilla bean, cedar, roasted coffee, dried apricots",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Collector"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Coffee", "Rye Whiskey"],
    brand: "LANCERO",
    size: "38 RG",
  },
  {
    id: 21,
    series: "Estate",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959672656-category-6---grand-cru.webp",
    badge: "Top Gift",
    title: "Exclusivo",
    format: "Toro Box-pressed",
    hexCode: "#E2DBCF",
    ringGauge: 54,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "2.14 cm",
    duration: "75-85 min",
    burnTime: "75–85 min",
    enjoymentTime: 80,
    intensity: 4,
    body: 4,
    flavors: "Chocolate, roasted coffee, cinnamon, hazelnut, oak wood",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Collector", "Gift Giver"],
    origin: {
      wrapper: "Habano 2000",
      binder: "Criollo 98",
      filler: "Corojo + Ometepe",
    },
    pairings: ["Rum", "Whiskey Sour", "Espresso"],
    brand: "TORO BOX-PRESSED",
    size: "54 RG",
  },
  {
    id: 22,
    series: "After Dark",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959869868-category-7-obsidian.webp",
    badge: "Top Gift",
    title: "Nocturne",
    format: "Toro",
    hexCode: "#1F1F1F",
    ringGauge: 54,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "2.14 cm",
    duration: "70-80 min",
    burnTime: "70–80 min",
    enjoymentTime: 75,
    intensity: 5,
    body: 5,
    flavors: "Dark praliné, roasted almonds, cacao, black pepper, rum",
    packaging: ["Box of 20", "Pack of 5", "Single"],
    for: ["Aficionado", "Gift Giver"],
    origin: {
      wrapper: "Habano 2000 Maduro",
      binder: "Criollo 98",
      filler: "Corojo + Ometepe",
    },
    pairings: ["Rum", "Whiskey Sour", "Cappuccino"],
    brand: "TORO",
    size: "54 RG",
  },
  {
    id: 23,
    series: "After Dark",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959869868-category-7-obsidian.webp",
    badge: "Aficionado",
    title: "Obsidian",
    format: "Robusto Gordo",
    hexCode: "#1F1F1F",
    ringGauge: 56,
    length: "5.5 in",
    lengthCm: "14 cm",
    diameterCm: "2.22 cm",
    duration: "65-75 min",
    burnTime: "65–75 min",
    enjoymentTime: 70,
    intensity: 5,
    body: 5,
    flavors: "Dark chocolate, espresso, leather, roasted coffee, oak wood",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Aficionado"],
    origin: {
      wrapper: "Corojo 99 Maduro",
      binder: "Criollo 98",
      filler: "Criollo + Piloto",
    },
    pairings: ["Whiskey", "Dark Rum", "Espresso"],
    brand: "ROBUSTO GORDO",
    size: "56 RG",
  },
  {
    id: 24,
    series: "After Dark",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959869868-category-7-obsidian.webp",
    badge: "Top Gift",
    title: "Midnight Gold",
    format: "Gran Toro",
    hexCode: "#1F1F1F",
    ringGauge: 58,
    length: "6.5 in",
    lengthCm: "16.5 cm",
    diameterCm: "2.30 cm",
    duration: "95-105 min",
    burnTime: "95–105 min",
    enjoymentTime: 100,
    intensity: 5,
    body: 4,
    flavors: "Caramel, roasted almonds, vanilla, leather, rum",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Gift Giver", "Aficionado"],
    origin: {
      wrapper: "Habano 2000 Maduro",
      binder: "Criollo 98",
      filler: "Ometepe + Corojo",
    },
    pairings: ["Rum", "Whiskey Sour", "Cappuccino"],
    brand: "GRAN TORO",
    size: "58 RG",
  },
  {
    id: 25,
    series: "Celebration",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959994269--catagory-8-celebration-gold-jubilee-edition.webp",
    badge: "Top Gift",
    title: "Jubilee Edition",
    format: "Robusto",
    hexCode: "#E1C67A",
    ringGauge: 50,
    length: "5.0 in",
    lengthCm: "12.7 cm",
    diameterCm: "1.98 cm",
    duration: "55-65 min",
    burnTime: "55–65 min",
    enjoymentTime: 60,
    intensity: 3,
    body: 4,
    flavors: "Cedar wood, cashew, roasted coffee, vanilla, caramel",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Gift Giver", "Novice"],
    origin: {
      wrapper: "Corojo 99",
      binder: "Criollo 98",
      filler: "Piloto Cubano",
    },
    pairings: ["Champagne", "Espresso", "Whiskey Sour"],
    brand: "ROBUSTO",
    size: "50 RG",
  },
  {
    id: 26,
    series: "Celebration",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959994269--catagory-8-celebration-gold-jubilee-edition.webp",
    badge: "Top Gift",
    title: "Puro Oro",
    format: "Robusto",
    hexCode: "#E1C67A",
    ringGauge: 50,
    length: "5.0 in",
    lengthCm: "12.7 cm",
    diameterCm: "1.98 cm",
    duration: "50-60 min",
    burnTime: "50–60 min",
    enjoymentTime: 55,
    intensity: 3,
    body: 4,
    flavors: "Cedar, roasted almonds, cream, caramel, vanilla",
    packaging: ["Box of 20", "Pack of 5", "Single"],
    for: ["Novice", "Gift Giver"],
    origin: {
      wrapper: "Corojo 99 Puro",
      binder: "Corojo 99 Puro",
      filler: "Corojo 99 Puro",
    },
    pairings: ["Espresso", "Coffee", "Whiskey"],
    brand: "ROBUSTO",
    size: "50 RG",
  },
  {
    id: 27,
    series: "Terrior",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779960039088-category-9-solstice.webp",
    badge: "Aficionado",
    title: "Terra Suprema",
    format: "Toro",
    hexCode: "#6F8C72",
    ringGauge: 54,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "2.14 cm",
    duration: "65-75 min",
    burnTime: "65–75 min",
    enjoymentTime: 70,
    intensity: 4,
    body: 4,
    flavors: "Earth, cedar wood, roasted nuts, black pepper, honey",
    packaging: ["Box of 20", "Box of 10"],
    for: ["Aficionado"],
    origin: {
      wrapper: "Criollo 98 Puro",
      binder: "Criollo 98 Puro",
      filler: "Criollo 98 Puro",
    },
    pairings: ["Whiskey", "Coffee", "Rum"],
    brand: "TORO",
    size: "54 RG",
  },
  {
    id: 28,
    series: "Terrior",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779960039088-category-9-solstice.webp",
    badge: "Top Gift",
    title: "Solstice",
    format: "Lancero",
    hexCode: "#6F8C72",
    ringGauge: 38,
    length: "7.5 in",
    lengthCm: "19 cm",
    diameterCm: "1.52 cm",
    duration: "80-90 min",
    burnTime: "80–90 min",
    enjoymentTime: 85,
    intensity: 2,
    body: 3,
    flavors: "Dried flowers, citrus, cedar, honey, vanilla",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Novice", "Collector"],
    origin: {
      wrapper: "Habano 2000 Puro",
      binder: "Habano 2000 Puro",
      filler: "Habano 2000 Puro",
    },
    pairings: ["Champagne", "Coffee", "Cocktails"],
    brand: "LANCERO",
    size: "38 RG",
  },
  {
    id: 29,
    series: "Terrior",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779960039088-category-9-solstice.webp",
    badge: "Novice",
    title: "Primera Cosecha",
    format: "Petit Corona",
    hexCode: "#6F8C72",
    ringGauge: 42,
    length: "4.5 in",
    lengthCm: "11.4 cm",
    diameterCm: "1.67 cm",
    duration: "35-45 min",
    burnTime: "35–45 min",
    enjoymentTime: 40,
    intensity: 2,
    body: 3,
    flavors: "Floral spice, cedar wood, almonds, brioche, honey",
    packaging: ["Box of 20", "Pack of 5", "Single"],
    for: ["Novice"],
    origin: {
      wrapper: "Piloto Cubano Puro",
      binder: "Piloto Cubano Puro",
      filler: "Piloto Cubano Puro",
    },
    pairings: ["Espresso", "Cappuccino", "Champagne"],
    brand: "PETIT CORONA",
    size: "42 RG",
  },
  {
    id: 30,
    series: "Terrior",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779960039088-category-9-solstice.webp",
    badge: "Novice",
    title: "Verde Classico",
    format: "Corona Larga",
    hexCode: "#6F8C72",
    ringGauge: 44,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "1.75 cm",
    duration: "55-65 min",
    burnTime: "55–65 min",
    enjoymentTime: 60,
    intensity: 2,
    body: 2,
    flavors: "Fresh herbs, cedar, cream, toasted bread, cashew",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Novice", "Gift Giver"],
    origin: {
      wrapper: "Ometepe Hybrid Puro",
      binder: "Ometepe Hybrid Puro",
      filler: "Ometepe Hybrid Puro",
    },
    pairings: ["Coffee", "Mojito", "Champagne"],
    brand: "CORONA LARGA",
    size: "44 RG",
  },
  {
    id: 31,
    series: "PLATINUM",
    image: "https://lpnrhpvmrnoqkzoxukov.supabase.co/storage/v1/object/public/product-images/1779959502876-catagory-3-celebration-series-platinum-celebration.webp",
    badge: "Novice",
    title: "Velarro Platinum Celebration",
    format: "Corona Larga",
    hexCode: "#6F8C72",
    ringGauge: 44,
    length: "6.0 in",
    lengthCm: "15.2 cm",
    diameterCm: "1.75 cm",
    duration: "55-65 min",
    burnTime: "55–65 min",
    enjoymentTime: 60,
    intensity: 2,
    body: 2,
    flavors: "Fresh herbs, cedar, cream, toasted bread, cashew",
    packaging: ["Box of 20", "Pack of 5"],
    for: ["Novice", "Gift Giver"],
    origin: {
      wrapper: "Ometepe Hybrid Puro",
      binder: "Ometepe Hybrid Puro",
      filler: "Ometepe Hybrid Puro",
    },
    pairings: ["Coffee", "Mojito", "Champagne"],
    brand: "CORONA LARGA",
    size: "44 RG",
  },
];

export default data;

export function getProductSlug(title: string) {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-+|-+$)/g, "");
}

export function findProductBySlug(slug?: string) {
  if (!slug) return undefined;
  return data.find((item) => getProductSlug(item.title) === slug);
}