import { Address } from "./address.types";

export const initialAddresses: Address[] = [
  {
    id: 1,
    title: "Address 1",
    name: "John Smith",
    address: "123 Maple St, Springfield",
    phone: "+1 (555) 012-3456",
    city: "Springfield",
    state: "IL",
    zip: "62704",
    country: "USA",
    isDefault: true,
  },
  {
    id: 2,
    title: "Address 2",
    name: "John Smith",
    address: "456 Oak Ave, Metropolis",
    phone: "+1 (555) 012-3456",
    city: "Metropolis",
    state: "IL",
    zip: "62704",
    country: "USA",
  },
  {
    id: 3,
    title: "Address 3",
    name: "John Smith",
    address: "789 Pine Rd, Gotham",
    phone: "+1 (555) 012-3456",
    city: "Gotham",
    state: "IL",
    zip: "62704",
    country: "USA",
  },
  {
    id: 4,
    title: "Address 4",
    name: "John Smith",
    address: "123 Maple St, Springfield",
    phone: "+1 (555) 012-3456",
    city: "Springfield",
    state: "IL",
    zip: "62704",
    country: "USA",
  },
];